version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - goconst
    - gocyclo
    - dupl
    - gosec

  settings:
    gocyclo:
      min-complexity: 15
    dupl:
      threshold: 100
    goconst:
      min-len: 3
      min-occurrences: 3

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
      - path: internal/version/version.go
        linters:
          - gochecknoglobals

formatters:
  enable:
    - gofmt
    - goimports

run:
  tests: true
  modules-download-mode: readonly

output:
  formats:
    text:
      path: stdout
      colors: true
      print-linter-name: true
      print-issued-lines: true
