linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - goconst
    - gocyclo
    - dupl
    - gosec

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    - path: internal/version/version.go
      linters:
        - gochecknoglobals
    # Exclude gosec false positives
    - linters:
        - gosec
      text: "G204: Subprocess launched with"
    - linters:
        - gosec
      text: "G304: Potential file inclusion"
    - linters:
        - gosec
      text: "G301: Expect directory permissions"
    - linters:
        - gosec
      text: "G306: Expect WriteFile permissions"
    # Exclude code duplication between similar load functions
    - linters:
        - dupl
      path: internal/workspace/(state|vscode)\.go
    # Exclude goconst for status string literals
    - linters:
        - goconst
      text: "string .*(main|error|success|failed|removed|skipped).* has .* occurrences"
    # Exclude high complexity for known complex functions
    - linters:
        - gocyclo
      path: internal/cli/(add|status|wt_create|wt_remove|wt_switch)\.go
    - linters:
        - gocyclo
      path: internal/workspace/removal\.go
    # Exclude unparam warnings (would require significant refactoring)
    - linters:
        - unparam
      path: internal/(cli|workspace)/

run:
  tests: true
  modules-download-mode: readonly
