version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - goconst
    - gocyclo
    - dupl
    - gosec

  settings:
    gocyclo:
      min-complexity: 15
    dupl:
      threshold: 100
    goconst:
      min-len: 3
      min-occurrences: 3

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
          - goconst
      - path: internal/version/version.go
        linters:
          - gochecknoglobals
      # Exclude gosec false positives
      - linters:
          - gosec
        text: "G104: Errors unhandled"
      - linters:
          - gosec
        text: "G204: Subprocess launched with"
      - linters:
          - gosec
        text: "G304: Potential file inclusion"
      - linters:
          - gosec
        text: "G301: Expect directory permissions"
      - linters:
          - gosec
        text: "G306: Expect WriteFile permissions"
      # Exclude code duplication between similar load functions
      - linters:
          - dupl
        path: internal/workspace/(state|vscode)\.go
      # Exclude goconst for status string literals
      - linters:
          - goconst
        text: "string .*(main|error|success|failed|removed|skipped|clean|modified|untracked|conflict|dev|unknown|windows).* has .* occurrences"
      # Exclude goconst for doctor check names
      - linters:
          - goconst
        text: "string .*(Orphaned worktrees|Orphaned repositories|State file|Workspace structure|Git installed|Git version).* has .* occurrences"
      # Exclude high complexity for known complex functions
      - linters:
          - gocyclo
        path: internal/cli/(add|status|wt_create|wt_remove|wt_switch)\.go
      - linters:
          - gocyclo
        path: internal/workspace/removal\.go
      - linters:
          - gocyclo
        path: internal/doctor/consistency\.go
      # Exclude unparam warnings (would require significant refactoring)
      - linters:
          - unparam
        path: internal/(cli|workspace)/
      # Exclude errcheck for defer cleanup calls and print functions
      - linters:
          - errcheck
        text: "Error return value of .*(Close|RemoveAll|fmt\\.Fprint).*is not checked"
      # Exclude staticcheck style warnings
      - linters:
          - staticcheck
        text: "ST1005: error strings should not be capitalized"
      - linters:
          - staticcheck
        text: "QF1003: could use tagged switch"

formatters:
  enable:
    - gofmt
    - goimports

run:
  tests: true
  modules-download-mode: readonly
